### ISSUE TITLE
Unable to push branch:unstaged

### ISSUE THREAD

**Issue by rishson** [sidekickcode/tracker#11]
stdout: On branch unstaged
Your branch is ahead of 'origin/unstaged' by 4 commits.
  (use "git push" to publish your local commits)
Changes not staged for commit:
    modified:   ../app/browser/src/directives/file.js

no changes added to commit

stderr: 
    at /Users/andy/code/sidekick/sk-deployed/app/common/shell.js:31:21
    at ChildProcess.exithandler (child_process.js:723:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at maybeClose (child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1057:5)
[daemon 10810] rpc call received: commitAndPush:["aac17f25-55fc-4369-882a-8c1979751c3b","872e2ae6-a376-412a-b89b-9ff7fde47ed8"]
[daemon 10810] error handling rpc call commitAndPush Error: 'Error: Command failed: /bin/sh -c git commit -m 'sidekick fixes'
' with error code 1, in path 'undefined'

**Comment by timruffles** [comment]
I'm a bit confused by this bug report, what is shell output and what is commentary? :)

**Comment by timruffles** [comment]
Fixed - I hadn't finished updating to do individual git adds
