### ISSUE TITLE
data.$on now too chatty in dev

### ISSUE THREAD

**Issue by rishson** [sidekickcode/tracker#160]
![screen shot 2015-12-07 at 3 39 00 p m](https://cloud.githubusercontent.com/assets/468596/11631182/b9a790aa-9cf8-11e5-8250-80885d8ccb55.png)

data.$on is firing alot more than the socket.io implementation. Previously, the ui would get a data event once per file anlaysis end event. Now we are getting 7 data.$on events firing which is causing the ui to thrash (because we recalculate analysis stats each time).

**Comment by timruffles** [comment]
as you mentioned, this is probably due to IPC not being torn down when page is refreshed. Whoops!
