### ISSUE TITLE
missing analysis events

### ISSUE THREAD

**Issue by timruffles** [sidekickcode/tracker#175]
here it's clear the events for gruntfile were not received

<img width="875" alt="screen shot 2016-01-06 at 14 32 09" src="https://cloud.githubusercontent.com/assets/249800/12144830/4e93023a-b482-11e5-9764-6c0d21b0d530.png">

**Comment by timruffles** [comment]
can easily reproduce with small repos!

**Comment by rishson** [comment]
Yep - can reproduce too. Weirdly, the file that fails for me is also the first in the sidebar list.
From my logs, its not that the analysis events for the first file are not received. The first file does not appear to have been analysed.

```
2016-01-07T13:35:21.186Z [gui-main 74604] [rpc] /common/rpc/index.js:349 node write { id: 62, type: 'result', result: [ 1, 2, 3, 4 ] }
2016-01-07T13:35:21.205Z [gui-main 74604] [analysis-session] [analysis] [[commit] ] [[analysis:push1.js] ] [[js-todos] ] /analysis/src/file_analysis.js:73 end with meta
```

This shows the rpc for the last analysed file's modifications, and then the first line of analysis (`push1.js`). However, first file to be analysed should be `new_unstaged.js` - which is the file that does not have any analysis events.

**Comment by timruffles** [comment]
looks good now.
