### ISSUE TITLE
Remove the need to bundle node

### ISSUE THREAD

**Issue by rishson** [sidekickcode/tracker#180]
The following should work just as well:

darwin

```
#!/bin/sh

#find the location of this script
SK_BIN_DIR="$( cd "$( dirname "$0" )" && pwd)"

ELECTRON_RUN_AS_NODE=true exec $SK_BIN_DIR/../../MacOS/Electron $SK_BIN_DIR/../app/cli/ui $@
```

**Comment by timruffles** [comment]
Oh nice! Let's give it a go

**Comment by rishson** [comment]
Yep - it works fine, but want to keep testing just to make sure there is no weirdness.
Saves us 20MB on the app size and a tonne of build steps.

**Comment by timruffles** [comment]
:) :) :)
