### ISSUE TITLE
ci run-with-no-sidekickrc

### ISSUE THREAD

**Issue by rishson** [sidekickcode/tracker#216]
If `sk init --create-configs` then copy each analyser's default config file to the repo root, e.g.

`jshint` copy the `jshint.json` file from `sidekick-jshint/config` to the repo root.

**Comment by rishson** [comment]
Each analyser should have a `defaults` dir that contains the default config file for the analyser.
This can be copied across on `sk init`.
On _ci_, if no `.sidekickrc` we should:
- [x] look for config files
- [x] work out what analysers to run

**Comment by rishson** [comment]
@timruffles - does this belong in `common/repoConfig`, e.g. if no `.sidekickrc` should we create a `repoConfig` based on above?

**Comment by timruffles** [comment]
probably, as both cli and gui can create
