### ISSUE TITLE
tab spaces while editing?

### ISSUE THREAD

**Issue by timruffles** [sidekickcode/tracker#48]
potential issue - does it auto-detect?

**Comment by rishson** [comment]
Initial research suggests determing tab width (if not tab char) can be problematic. Initially, I might go with user configuration for a) tab char b) no of spaces if tab is not tab char

**Comment by rishson** [comment]
After feedback at asyncjs, I think we should look for .editorrc in repo to get tab/spaces info and trailing newline etc.
If not present then use app settings.

**Comment by timruffles** [comment]
Sure, and it seems like the below would be a good UX for tabbed files.

``` javascript
var tabbedLines = /^\t/.test(content)
var spacedLines = /^ /.test(content)
var mode = 'spaces';
if(tabbedLines && !spacedLines) {
  mode = "tabs";
}
```

**Comment by rishson** [comment]
Of course I mean `.editorconfig` not `.editorrc`.
So order of precedence will be:
- .editorconfig
- check some files to see if we can default the app settings to tabs/spaces.
- user can always change app settings from the settings ui if we have guessed incorrectly.

**Comment by rishson** [comment]
At a later date, we could add a feature to check all files for conformance to a .editorconfig file and autofix.

**Comment by timruffles** [comment]
#2 - 'check some files' - wouldn't it be better to do this on a per-file
basis if .editorconfig or user settings are not present? Seems more
accurate that trying to generalise to app-wide?

**Comment by rishson** [comment]
Yeah, so I've implemented:
- `.editorConfig`
- derrive for current file
- fallback to global app setting

Weirdly, https://regex101.com/r/yQ0yM6/1 works, but not in code!? When the same regex is run in code, it returns only 2 matches with 2 spaces. This is just wrong, so I think its to do with the way the fileContents are being passed around.
