### ISSUE TITLE
Autoupdate failing to install

### ISSUE THREAD

**Issue by rishson** [sidekickcode/tracker#65]
Download server reports 0.10.1 is being pulled, but the UI fails to install the update.

**Comment by rishson** [comment]
[gui-main 671] start at Wed Sep 30 2015 10:19:57 GMT+0100 (BST)
[gui-main 671] ENV: ELIDDED 
[gui-main 671] runtime settings: {"version":"0.9.1","googleAnalyticsUa":"ELIDDED","analyticsPhonyDomain":"desktop.sidekickjs.com","daemonLogPath":"/tmp/sk-daemon","cliLogPath":"/tmp/sk-cli","browserLogPath":"/tmp/sk-browser","rendererLogPath":"/tmp/sk-renderer","commonLogPath":"/tmp/sk-common","port":42042,"installedBinPath":"/Applications/Sidekick.app/Contents/Resources/bin","iojsPath":"/Applications/Sidekick.app/Contents/Resources/vendor/iojs/bin/iojs","electronPath":"/Applications/Sidekick.app/Contents/MacOS/Electron","analysers":{"js":["js-todos","jshint","jscs","eslint"],"coffee":["coffeelint"]},"analyserColours":{"js":{"js-todos":"","jshint":"teal","jscs":"yellow","eslint":"purple"},"coffee":{"coffeelint":"brown"},"ruby":{"rubocop":"red"}}}
[gui-main 671] loading config file: /Users/anthony/Library/Application Support/sidekick/SidekickConfig.json
[gui-main 671] config file contents on load: {"userSettings":{"keyBindings":"default","editorTheme":"default","sidebarTheme":{"colour":"pale-elm","contrast":"sk-menu-light"},"collapseCode":"true","currentPush":{"showUnstagedFiles":true}},"update":{"lastUpdated":"2015-05-14T10:39:06.602Z","updatePeriod":"daily"},"repos":[{"path":"/Users/anthony/work/development/frontend/accelus-admin-app"}]}
[gui-main 671] config file contents after: {"userSettings":{"keyBindings":"default","editorTheme":"default","sidebarTheme":{"colour":"pale-elm","contrast":"sk-menu-light"},"collapseCode":"true","currentPush":{"showUnstagedFiles":true}},"update":{"lastUpdated":"2015-05-14T10:39:06.602Z","updatePeriod":"daily"},"repos":[{"path":"/Users/anthony/work/development/frontend/accelus-admin-app"}]}
[gui-main 671] read config
[gui-main 671] trying to start daemon
[daemon-api] opts are: {"port":42042,"spawnDaemon":true,"onResolutionCallback":false}
[daemon-api] acquiring daemon
[gui-main 671] last updated date is valid
[gui-main 671] update check is required
[gui-main 671] update: setting feed url to: http://updates.sidekickjs.com/releases/latest?current_version=0.9.1&os=darwin
[gui-main 671] update: checking for updates..
[gui-main 671] starting browser debug
[daemon-api] no answer on daemon socket
[daemon-api] daemon is not up
[daemon-api] no answer on daemon socket
[daemon-api] no answer on daemon socket
[daemon-api] no answer on daemon socket
[daemon-api] daemon socket open
[daemon-api] attempting to open socket to daemon: http://localhost:42042
[daemon-api] connected to daemon on port 42042
[daemon-api] have io, starting rpc
rpc server heard connection
[gui-main 671] heard sidekick ready
[gui-main 671] browser window loaded
[gui-main 671] update: setting feed url to: http://updates.sidekickjs.com/releases/latest?current_version=0.9.1&os=darwin
[gui-main 671] update: checking for updates..
[gui-main 671] autoupdater: error received - The command is disabled and cannot be executed: (null)
[gui-main 671] {"0":{"sender":{"_events":{"checking-for-update":[null,null],"update-available":[null,null],"update-not-available":[null,null],"update-downloaded":[null,null],"error":[null,null]},"_eventsCount":6}},"1":"The command is disabled and cannot be executed: (null)"}
[gui-main 671] autoupdater: error received - The command is disabled and cannot be executed: (null)
[gui-main 671] {"0":{"sender":{"_events":{"checking-for-update":[null,null],"update-available":[null,null],"update-not-available":[null,null],"update-downloaded":[null,null],"error":[null,null]},"_eventsCount":6}},"1":"The command is disabled and cannot be executed: (null)"}
[gui-main 671] autoupdater: checking for update..
[gui-main 671] autoupdater: checking for update..
[gui-main 671] update: setting feed url to: http://updates.sidekickjs.com/releases/latest?current_version=0.9.1&os=darwin
[gui-main 671] update: checking for updates..
[gui-main 671] autoupdater: error received - The command is disabled and cannot be executed: (null)
[gui-main 671] {"0":{"sender":{"_events":{"checking-for-update":[null,null,null],"update-available":[null,null,null],"update-not-available":[null,null,null],"update-downloaded":[null,null,null],"error":[null,null,null]},"_eventsCount":6}},"1":"The command is disabled and cannot be executed: (null)"}
[gui-main 671] autoupdater: error received - The command is disabled and cannot be executed: (null)
[gui-main 671] {"0":{"sender":{"_events":{"checking-for-update":[null,null,null],"update-available":[null,null,null],"update-not-available":[null,null,null],"update-downloaded":[null,null,null],"error":[null,null,null]},"_eventsCount":6}},"1":"The command is disabled and cannot be executed: (null)"}
[gui-main 671] autoupdater: error received - The command is disabled and cannot be executed: (null)
[gui-main 671] {"0":{"sender":{"_events":{"checking-for-update":[null,null,null],"update-available":[null,null,null],"update-not-available":[null,null,null],"update-downloaded":[null,null,null],"error":[null,null,null]},"_eventsCount":6}},"1":"The command is disabled and cannot be executed: (null)"}
[gui-main 671] autoupdater: update available, downloading..
[gui-main 671] autoupdater: update available, downloading..
[gui-main 671] autoupdater: update available, downloading..
[gui-main 671] autoupdater: update downloaded.
[gui-main 671] autoupdater: 0.10.1 release (2015-01-14T10:20:00+00:00)
[gui-main 671] autoupdater: update downloaded.
[gui-main 671] autoupdater: 0.10.1 release (2015-01-14T10:20:00+00:00)
[gui-main 671] autoupdater: update downloaded.
[gui-main 671] autoupdater: 0.10.1 release (2015-01-14T10:20:00+00:00)
[gui-main 671] main window closed
[gui-main 1076] start at Wed Sep 30 2015 10:25:17 GMT+0100 (BST)
[gui-main 1076] ENV: ELIDDED
[gui-main 1076] runtime settings: {"version":"0.10.1","googleAnalyticsUa":"ELIDDED","analyticsPhonyDomain":"desktop.sidekickjs.com","daemonLogPath":"/tmp/sk-daemon","cliLogPath":"/tmp/sk-cli","browserLogPath":"/tmp/sk-browser","rendererLogPath":"/tmp/sk-renderer","commonLogPath":"/tmp/sk-common","port":42042,"installedBinPath":"/Applications/Sidekick.app/Contents/Resources/bin","iojsPath":"/Applications/Sidekick.app/Contents/Resources/vendor/iojs/bin/iojs","electronPath":"/Applications/Sidekick.app/Contents/MacOS/Electron","analysers":{"js":["js-todos","jshint","jscs","eslint"],"coffee":["coffeelint"]},"analyserColours":{"js":{"js-todos":"","jshint":"teal","jscs":"yellow","eslint":"purple"},"coffee":{"coffeelint":"brown"},"ruby":{"rubocop":"red"}}}
[gui-main 1076] loading config file: /Users/anthony/Library/Application Support/sidekick/SidekickConfig.json
[gui-main 1076] config file contents on load: {"userSettings":{"keyBindings":"default","editorTheme":"default","sidebarTheme":{"colour":"pale-elm","contrast":"sk-menu-light"},"collapseCode":"true","currentPush":{"showUnstagedFiles":true}},"update":{"lastUpdated":"2015-05-14T10:39:06.602Z","updatePeriod":"daily"},"repos":[{"path":"/Users/anthony/work/development/frontend/accelus-admin-app"}]}
[gui-main 1076] config file contents after: {"userSettings":{"keyBindings":"default","editorTheme":"default","sidebarTheme":{"colour":"pale-elm","contrast":"sk-menu-light"},"collapseCode":"true","currentPush":{"showUnstagedFiles":true}},"update":{"lastUpdated":"2015-05-14T10:39:06.602Z","updatePeriod":"daily"},"repos":[{"path":"/Users/anthony/work/development/frontend/accelus-admin-app"}]}
[gui-main 1076] read config
[gui-main 1076] trying to start daemon
[daemon-api] opts are: {"port":42042,"spawnDaemon":true,"onResolutionCallback":false}
[daemon-api] acquiring daemon
[gui-main 1076] last updated date is valid
[gui-main 1076] update check is required
[gui-main 1076] update: setting feed url to: http://updates.sidekickjs.com/releases/latest?current_version=0.10.1&os=darwin
[gui-main 1076] update: checking for updates..
[gui-main 1076] starting browser debug
[gui-main 1076] autoupdater: checking for update..
[daemon-api] daemon socket open
[daemon-api] daemon is up
[daemon-api] attempting to open socket to daemon: http://localhost:42042
[daemon-api] connected to daemon on port 42042
[daemon-api] have io, starting rpc
rpc server heard connection
[gui-main 1076] heard sidekick ready
[gui-main 1076] browser window loaded
[gui-main 1076] autoupdater: update not available.

**Comment by pauliusuza** [comment]
I have the same issue with my app, could you please share what was the solution?

**Comment by rishson** [comment]
@pauliusuza If memory serves (6 months ago) it was the update server not having the correct LATEST_VERSION set. If autoupdate is working for you, then you should be on version 0.16.1.
