### ISSUE TITLE
Create an option to load with double scale for linux Hidpi monitors

### ISSUE THREAD

**Issue by campbellwmorgan** [sidekickcode/tracker#80]
![sidekickscaling](https://cloud.githubusercontent.com/assets/1377367/10341276/faff8304-6d0b-11e5-96af-7d64f788bb2d.png)

**Comment by rishson** [comment]
https://github.com/atom/electron/issues/615#issuecomment-116366096

**Comment by timruffles** [comment]
thanks @campbellwmorgan

**Comment by rishson** [comment]
need electron 0.33.5

**Comment by rishson** [comment]
Bumped electron version to 0.33.9. Don't want to disable hidpi or or try to guess resolution.
https://github.com/atom/atom/issues/3826
